" Store as ~/.emacs

set nocompatible

"
"  Vundle
" https://github.com/gmarik/vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
let g:vundle_default_git_proto = 'git'
Bundle 'gmarik/vundle'

" Load plugins
Bundle 'tomasr/molokai'

" Confiure plugins
colorscheme molokai

" Turn on syntax hilighting
set syntax=on

" Turn on line numbers
set number


filetype plugin indent on     " required! (for vundle)

" Save to system clipboard
set clipboard=unnamedplus

source ~/.vimrc_local
