" Store as ~/.emacs
" Andrew Z Allen

set nocompatible

" Vundle {{{
" https://github.com/gmarik/vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
let g:vundle_default_git_proto = 'git'
Bundle 'gmarik/vundle'

" Load plugins
Bundle 'tomasr/molokai'

" Confiure plugins
colorscheme molokai
" }}}
" Vim UI {{{
" Turn on syntax hilighting
set syntax=on

" Turn on line numbers
set number

" Set reasonable tab settings
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

" Hilight the current line
set cursorline

" Turn on modelines
set modelines=1

" Only redraw when absolutely necessary
set lazyredraw

" Show matching characters ([{}])
set showmatch

" Incremental search
set incsearch

" Hilight as searching
" This will keep the hilighting active until disabled
set hlsearch

filetype plugin indent on     " required! (for vundle)

" Save to system clipboard
set clipboard=unnamedplus
" }}}

source ~/.vimrc_local
